### PR TITLE
Add Django 1.7 support

### PR DESCRIPTION
**Pull request by richardxia**
This PR adds support for Django 1.7 by generating 1.7-style migration files. The [final release](http://south.readthedocs.org/en/latest/releasenotes/1.0.html) of South adds a shim which allows you to name the folder containing South-style migrations to `south_migrations/`, allowing you to simultaneously keep both Django 1.7-style and South-style migrations in an app.

### CODE REVIEW

**Comment by chrisspen** [comment]
By moving legacy migrations to a separate folder, won't that break pre-1.7 installs?

**Comment by richardxia** [comment]
No, South has provided a specific [migration path](http://south.readthedocs.org/en/latest/releasenotes/1.0.html#library-migration-path) so that it recognizes if migrations are located in a folder named `south_migrations/` rather than `migrations/`. This was intentionally done so that libraries can provide both South-style and Django 1.7-style migrations at the same time.

**Comment by chrisspen** [comment]
Thanks for the contribution.

**Comment by richardxia** [comment]
Thanks for accepting the patch!

**Pull request merged**
